/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JRegister.java
 *
 * Created on 02-nov-2012, 7:09:28
 */
package Clase_2;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Franklin
 */
public class JRegister extends javax.swing.JFrame {

    ArrayList<Usuarios> informacion=new ArrayList<Usuarios>();
    String path="";
    public JRegister() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnImagen = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Password:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 310, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 30, 110, 40);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(120, 200, 110, 30);

        jLabel3.setText("Image de Perfil:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 80, 100, 20);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 340, 110, 30);

        btnRegistrar.setText("Registrarse");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(120, 430, 100, 30);

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagen);
        lblImagen.setBounds(210, 80, 60, 60);

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 100, 20);

        btnImagen.setText("Elegir Imagen");
        btnImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagenMouseClicked(evt);
            }
        });
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnImagen);
        btnImagen.setBounds(70, 110, 110, 30);

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(120, 270, 110, 30);

        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 250, 100, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-342)/2, (screenSize.height-578)/2, 342, 578);
    }// </editor-fold>//GEN-END:initComponents

private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
    if(this.txtName.getText().isEmpty() || this.txtPassword.getText().isEmpty() ||
            this.txtApellido.getText().isEmpty() || this.path.isEmpty()){
        System.out.println("Nombre: "+this.txtName.getText().isEmpty()+" - "+
                "Password: "+this.txtPassword.getText().isEmpty()+" - "+
                "Apellido: "+this.txtApellido.getText().isEmpty()+" - "+
                "Path: "+this.path.isEmpty());
        JOptionPane.showMessageDialog(this, "El código o la contraseña están vacios",
                "Información necesaria",JOptionPane.WARNING_MESSAGE);
    }else{
        Usuarios temp=new Usuarios(this.txtName.getText(),this.txtPassword.getText(),
                this.txtApellido.getText(),this.path);
        this.informacion.add(temp);
        
        //this.informacion.add(new Usuarios(this.txtName.getText(),this.txtPassword.getText()));
        JOptionPane.showMessageDialog(this,"Información guardada con éxito","Estás registrado",
                JOptionPane.INFORMATION_MESSAGE);
        
        this.setVisible(false);
        
    }
}//GEN-LAST:event_btnRegistrarMouseClicked

private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked

    
}//GEN-LAST:event_lblImagenMouseClicked

private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtApellidoActionPerformed

private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnImagenActionPerformed

private void btnImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagenMouseClicked
    this.path="";
    JFileChooser file=new JFileChooser();
    file.setDialogTitle("Eliga una imagen");
    file.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int val=file.showOpenDialog(this);
    if(val==JFileChooser.APPROVE_OPTION){
        String temp=file.getSelectedFile().getAbsolutePath();
        System.out.println(temp);
        colocarImagen(temp);
        this.path=temp;
    }else{
        JOptionPane.showMessageDialog(this, "No ha seleccionado ningún archivo","Información inválida",
                JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public boolean validarInfo(String name,String pass){
        for(int i=0;i<informacion.size();i++){
            if(this.txtName.getText().equals(informacion.get(i).name)&&
                    this.txtPassword.getText().equals(informacion.get(i).password)){
                return true;
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void colocarImagen(String temp) {
        ImageIcon image=new ImageIcon(temp);
        ImageIcon image2=new ImageIcon(image.getImage().getScaledInstance(this.lblImagen.getWidth(), 
                this.lblImagen.getHeight(), Image.SCALE_DEFAULT));
        this.lblImagen.setIcon(image2);
    }
    public ArrayList<Usuarios> getInfo(){
        return this.informacion;
    }
}
